# frozen_string_literal: true

# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# Generated by ChatGPT
task_titles = [
  'Buy groceries (Get milk, eggs, and bread)',
  'Finish homework (Complete math assignment)',
  'Call mom',
  'Pay bills',
  'Walk the dog',
  'Write a blog post',
  'Schedule dentist appointment',
  'Water the plants',
  'Read a book',
  'Clean the garage',
  'Exercise for 30 minutes',
  'Cook dinner',
  'Update resume',
  'Attend virtual meeting',
  'Fix leaky faucet',
  'Organize closet',
  'Research vacation destinations',
  'Send birthday card',
  'Learn a new recipe',
  'Practice guitar',
  'Sort emails',
  'Plan weekend activities',
  'Review project proposal',
  'Watch a documentary',
  'Declutter desk',
  'Create a budget',
  'Call a friend',
  'Set up online banking',
  'Explore local hiking trails',
  'Try a new hobby'
]

task_titles.each do |title|
  Task.find_or_create_by!(
    title:,
    subtitle: 'Discipline is the key to success',
    due_at: 2.days.from_now.beginning_of_day,
    priority: Task.priorities.keys.sample,
    status: Task.statuses.keys.sample
  )
end
